Repository codestates-seb/seb42_main_029, pull requests merged in 2023-04, with the labels that each got.

#164 feat : 주문시 장바구니가 비워지도록 수정
  src/main/java/com/k5/modudogcat/domain/cart/repository/CartProductRepository.java
  src/main/java/com/k5/modudogcat/domain/cart/service/CartService.java
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderService.java
Labels: backend, feat

#163 Fe/min4 주문생성까지
  client/src/App.js
  client/src/components/header/Header.jsx
  client/src/components/header/MobileMenu.jsx
  client/src/components/pay/BtnGrp.jsx
  client/src/components/pay/BuyerInfo.jsx
  client/src/components/pay/PayInfo.jsx
  client/src/components/pay/ReceiverInfo.jsx
  client/src/components/pay/payComplete/PayCompleteForm.jsx
  client/src/pages/Cart.jsx
  client/src/pages/Main.jsx
  client/src/pages/Pay.jsx
  client/src/pages/PayComplete.jsx
  client/src/pages/Product.jsx
  client/src/pages/ProductInfo.jsx
Labels: frontend, feat

#166 docs : README 생성 & 콘솔 제거
  README.md
  client/README.md
  client/src/components/pay/payComplete/PayCompleteForm.jsx
  client/src/pages/Cart.jsx
  client/src/pages/ProductInfo.jsx
Labels: docs

#167 fix/be/order
  src/main/java/com/k5/modudogcat/domain/cart/controller/CartController.java
  src/main/java/com/k5/modudogcat/domain/cart/service/CartService.java
  src/main/java/com/k5/modudogcat/domain/order/controller/OrderController.java
  src/main/java/com/k5/modudogcat/domain/order/repository/OrderRepository.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderService.java
  src/main/java/com/k5/modudogcat/domain/product/repository/ProductRepository.java
  src/main/java/com/k5/modudogcat/domain/product/service/ProductService.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/resources/application-local.yml
Labels: bug, backend

#168 fix : 판매자 주문 목록 조회 완료
  build.gradle
  src/main/java/com/k5/modudogcat/domain/admin/service/AdminService.java
  src/main/java/com/k5/modudogcat/domain/order/controller/OrderProductController.java
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderDto.java
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderProductDto.java
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
  src/main/java/com/k5/modudogcat/domain/order/mapper/OrderProductMapper.java
  src/main/java/com/k5/modudogcat/domain/order/repository/OrderProductRepository.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderProductService.java
  src/main/java/com/k5/modudogcat/domain/product/dto/ProductDto.java
  src/main/java/com/k5/modudogcat/domain/product/repository/ProductRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  src/main/java/com/k5/modudogcat/domain/seller/repository/SellerRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/queryDslConfig/OrderCustomRepository.java
  src/main/java/com/k5/modudogcat/queryDslConfig/OrderCustomRepositoryImpl.java
  src/main/java/com/k5/modudogcat/queryDslConfig/QueryDslConfig.java
Labels: bug, backend, feat

#169 fix : Modify descending
  src/main/java/com/k5/modudogcat/domain/admin/service/AdminService.java
  src/main/java/com/k5/modudogcat/domain/order/controller/OrderProductController.java
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderProductDto.java
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderProductService.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
Labels: bug, backend

#175 Feat/be/order
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/k5/modudogcat/domain/admin/service/AdminService.java
  src/main/java/com/k5/modudogcat/domain/order/controller/OrderProductController.java
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderDto.java
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderProductDto.java
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
  src/main/java/com/k5/modudogcat/domain/order/mapper/OrderMapper.java
  src/main/java/com/k5/modudogcat/domain/order/mapper/OrderProductMapper.java
  src/main/java/com/k5/modudogcat/domain/order/repository/OrderProductRepository.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderProductService.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderService.java
  src/main/java/com/k5/modudogcat/domain/product/dto/ProductDto.java
  src/main/java/com/k5/modudogcat/domain/product/repository/ProductRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  src/main/java/com/k5/modudogcat/domain/seller/entity/Seller.java
  src/main/java/com/k5/modudogcat/domain/seller/repository/SellerRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/queryDslConfig/OrderCustomRepository.java
  src/main/java/com/k5/modudogcat/queryDslConfig/OrderCustomRepositoryImpl.java
  src/main/java/com/k5/modudogcat/queryDslConfig/QueryDslConfig.java
  src/main/resources/application-server.yml
Labels: bug, backend

#176 fix : Modify descending
  src/main/java/com/k5/modudogcat/domain/admin/dto/AdminDto.java
  src/main/java/com/k5/modudogcat/domain/cart/service/CartService.java
  src/main/java/com/k5/modudogcat/domain/order/controller/OrderController.java
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderProductDto.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderProductService.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderService.java
  src/main/java/com/k5/modudogcat/domain/product/service/ProductService.java
  src/main/java/com/k5/modudogcat/domain/review/service/ReviewService.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
  src/main/java/com/k5/modudogcat/util/OrderProductStatusDeserializer.java
Labels: backend, feat

#177 Feat/be/order
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/k5/modudogcat/domain/admin/service/AdminService.java
  src/main/java/com/k5/modudogcat/domain/cart/dto/CartProductDto.java
  src/main/java/com/k5/modudogcat/domain/cart/entity/CartProduct.java
  src/main/java/com/k5/modudogcat/domain/cart/mapper/CartMapper.java
  src/main/java/com/k5/modudogcat/domain/order/controller/OrderProductController.java
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderDto.java
  src/main/java/com/k5/modudogcat/domain/order/mapper/OrderProductMapper.java
  src/main/java/com/k5/modudogcat/domain/order/repository/OrderProductRepository.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderProductService.java
  src/main/java/com/k5/modudogcat/domain/product/dto/ProductDto.java
  src/main/java/com/k5/modudogcat/domain/product/repository/ProductRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  src/main/java/com/k5/modudogcat/domain/seller/entity/Seller.java
  src/main/java/com/k5/modudogcat/domain/seller/repository/SellerRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/queryDslConfig/OrderCustomRepository.java
  src/main/java/com/k5/modudogcat/queryDslConfig/OrderCustomRepositoryImpl.java
  src/main/java/com/k5/modudogcat/queryDslConfig/QueryDslConfig.java
  src/main/resources/application-server.yml
Labels: bug, backend, feat

#178 Feat/be/order
  src/main/java/com/k5/modudogcat/domain/cart/service/CartService.java
Labels: bug, backend

#179 fix : Modify Id
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderProductService.java
  src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
Labels: bug, backend

#180 fix : Modify descending
  src/main/java/com/k5/modudogcat/domain/admin/service/AdminService.java
  src/main/java/com/k5/modudogcat/domain/cart/service/CartService.java
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderProductService.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderService.java
  src/main/java/com/k5/modudogcat/domain/product/service/ProductService.java
  src/main/java/com/k5/modudogcat/domain/review/service/ReviewService.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
Labels: bug, backend

#181 Feat/be/order : 주문 생성 dto 수정
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderDto.java
Labels: bug, backend

#182 fix : Modify deserialized
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
Labels: bug, backend

#183 fix : Modify deserialized
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderProductDto.java
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
Labels: bug, backend

#184 fix : Modify auditable:
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
Labels: bug, backend

#185 fix : Modify enum type
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
Labels: bug, backend

#186 fix : Modify dateTime
  src/main/java/com/k5/modudogcat/audit/Auditable.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderProductService.java
Labels: bug, backend

#187 fix : Modify dateTime
  src/main/java/com/k5/modudogcat/audit/Auditable.java
Labels: bug, backend

#188 fix : 후기 작성 및 구매자, 상품별 후기 조회 기능 구현
  src/main/java/com/k5/modudogcat/domain/review/controller/ReviewController.java
  src/main/java/com/k5/modudogcat/domain/review/dto/ReviewDto.java
  src/main/java/com/k5/modudogcat/domain/review/entity/Review.java
  src/main/java/com/k5/modudogcat/domain/review/entity/reviewImage/Image.java
  src/main/java/com/k5/modudogcat/domain/review/entity/reviewImage/ImageController.java
  src/main/java/com/k5/modudogcat/domain/review/entity/reviewImage/ImageRepository.java
  src/main/java/com/k5/modudogcat/domain/review/entity/reviewImage/ImageService.java
  src/main/java/com/k5/modudogcat/domain/review/mapper/ReviewMapper.java
  src/main/java/com/k5/modudogcat/domain/review/repository/ReviewRepository.java
  src/main/java/com/k5/modudogcat/domain/review/service/ReviewService.java
  src/main/java/com/k5/modudogcat/domain/user/repository/UserRepository.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
  src/main/resources/application-local.yml
Labels: backend, feat

#189 feat : Add 상품 삭제 시 삭제 권한 검증 기능 구현
  src/main/java/com/k5/modudogcat/domain/admin/service/AdminService.java
  src/main/java/com/k5/modudogcat/domain/product/controller/ProductController.java
  src/main/java/com/k5/modudogcat/domain/product/service/ProductService.java
  src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
Labels: backend, feat

#190 fix : 후기 삭제(구매자 마이페이지)
  src/main/java/com/k5/modudogcat/domain/review/controller/ReviewController.java
Labels: backend, feat

#191 fix : 후기 삭제(구매자 마이페이지) URI 수정
  src/main/java/com/k5/modudogcat/domain/review/controller/ReviewController.java
Labels: bug, backend

#193 feat : 관리자의 후기 삭제
  src/main/java/com/k5/modudogcat/domain/review/controller/ReviewController.java
  src/main/java/com/k5/modudogcat/domain/review/service/ReviewService.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
  src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
Labels: backend, feat

#198 fix : 장바구니 중복 담기 에러 수정
  src/main/java/com/k5/modudogcat/domain/cart/service/CartService.java
Labels: bug, backend

#201 fix : 운송장번호 유효성 검사 추가
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderProductDto.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
Labels: backend, feat

#205 fix : 관리자 검증 추가
  src/main/java/com/k5/modudogcat/domain/review/service/ReviewService.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
Labels: bug, backend
