Repository codestates-seb/seb42_main_029, pull requests merged in 2023-03, with the labels that each got.

#82 Fe/dongwon
  client/public/images/img_dummy1.png
  client/public/images/img_dummy1_more.jpeg
  client/public/images/img_dummy2.png
  client/public/images/img_dummy3.png
  client/public/images/img_dummy4.png
  client/public/images/img_dummy5.png
  client/public/images/img_dummy6.png
  client/public/images/img_dummy7.png
  client/public/images/img_dummy8.png
  client/src/App.css
  client/src/App.js
  client/src/assets/dummy/dummy.json
  client/src/assets/productImage/img_dummy1.png
  client/src/assets/productImage/img_dummy1_more.jpeg
  client/src/assets/productImage/img_dummy2.png
  client/src/assets/productImage/img_dummy3.png
  client/src/assets/productImage/img_dummy4.png
  client/src/assets/productImage/img_dummy5.png
  client/src/assets/productImage/img_dummy6.png
  client/src/assets/productImage/img_dummy7.png
  client/src/assets/productImage/img_dummy8.png
  client/src/components/Category.jsx
  client/src/pages/Product.jsx
  client/src/pages/ProductInfo.jsx
  client/src/pages/Shop.jsx
Labels: frontend

#79 Docs: 회원 CRUD - API 명세서 생성
  modudogcat/build.gradle
  modudogcat/src/docs/asciidoc/index.adoc
  modudogcat/src/docs/asciidocs/index.adoc
  modudogcat/src/main/java/com/k5/modudogcat/ModudogcatApplication.java
  modudogcat/src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
  modudogcat/src/main/java/com/k5/modudogcat/user/Mapper/UserMapper.java
  modudogcat/src/main/java/com/k5/modudogcat/user/controller/UserController.java
  modudogcat/src/main/java/com/k5/modudogcat/user/dto/UserDto.java
  modudogcat/src/main/java/com/k5/modudogcat/user/entity/User.java
  modudogcat/src/main/java/com/k5/modudogcat/user/repository/UserRepository.java
  modudogcat/src/main/java/com/k5/modudogcat/user/service/UserService.java
  modudogcat/src/test/java/com/k5/modudogcat/slice/member/UserUserControllerRestdocsTest.java
  modudogcat/src/test/java/com/k5/modudogcat/util/ApiDocumentUtils.java
Labels: backend, docs, feat, test

#81 Dosc: Rest Docs를 활용한 Seller API 문서 생성
  modudogcat/build.gradle
  modudogcat/src/docs/asciidoc/index.adoc
  modudogcat/src/main/java/com/k5/modudogcat/domain/anwser/controller/AnswerController.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/anwser/dto/AnswerDto.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/anwser/entity/Answer.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/seller/dto/SellerDto.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/seller/entity/Seller.java
  modudogcat/src/main/resources/static/docs/index.html
  modudogcat/src/test/java/com/k5/modudogcat/slice/answer/AnswerControllerTest.java
  modudogcat/src/test/java/com/k5/modudogcat/slice/seller/SellerControllerTest.java
Labels: chore, backend, docs, feat, test

#84 Feat: Answer Stub Data 이용한 Controller 및 Dto, Entity 구현
  modudogcat/build.gradle
  modudogcat/src/docs/asciidoc/index.adoc
  modudogcat/src/main/java/com/k5/modudogcat/domain/anwser/controller/AnswerController.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/anwser/entity/Answer.java
Labels: backend, docs, feat, test

#85 Feat : AdminController, Dto 및 ControllerTest 구현
  modudogcat/build.gradle
  modudogcat/src/docs/asciidoc/index.adoc
  modudogcat/src/main/java/com/k5/modudogcat/domain/admin/controller/AdminController.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/admin/dto/AdminDto.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/anwser/controller/AnswerController.java
  modudogcat/src/test/java/com/k5/modudogcat/slice/admin/AdminControllerTest.java
Labels: backend, feat

#91 chore : Deploy 파일 생성
  modudogcat/appspec.yml
  modudogcat/buildspec.yml
  modudogcat/scripts/initialize.sh
  modudogcat/scripts/server_clear.sh
  modudogcat/scripts/server_start.sh
  modudogcat/scripts/server_stop.sh
Labels: chore, backend

#92 Feat/be/member(미작성)
  modudogcat/build.gradle
  modudogcat/src/main/java/com/k5/modudogcat/domain/user/Mapper/UserMapper.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/user/controller/UserController.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/user/dto/UserDto.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/user/entity/User.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/user/repository/UserRepository.java
  modudogcat/src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
  modudogcat/src/main/java/com/k5/modudogcat/security/config/SecurityConfig.java
  modudogcat/src/main/java/com/k5/modudogcat/security/dto/LoginDto.java
  modudogcat/src/main/java/com/k5/modudogcat/security/filter/JwtAuthenticationFilter.java
  modudogcat/src/main/java/com/k5/modudogcat/security/filter/JwtVerificationFilter.java
  modudogcat/src/main/java/com/k5/modudogcat/security/handler/CustomLogoutHandler.java
  modudogcat/src/main/java/com/k5/modudogcat/security/handler/UserAccessDeniedHandler.java
  modudogcat/src/main/java/com/k5/modudogcat/security/handler/UserAuthenticationEntryPoint.java
  modudogcat/src/main/java/com/k5/modudogcat/security/handler/UserAuthenticationFailureHandler.java
  modudogcat/src/main/java/com/k5/modudogcat/security/handler/UserAuthenticationSuccessHandler.java
  modudogcat/src/main/java/com/k5/modudogcat/security/jwt/JwtTokenizer.java
  modudogcat/src/main/java/com/k5/modudogcat/security/userdetails/UserDetailsServiceImpl.java
  modudogcat/src/main/java/com/k5/modudogcat/security/util/CustomAuthorityUtils.java
  modudogcat/src/main/java/com/k5/modudogcat/security/util/ErrorResponder.java
  modudogcat/src/main/java/com/k5/modudogcat/user/dto/UserDto.java
  modudogcat/src/main/resources/application.yml
Labels: backend, feat, refactor

#96 docs : delete README.md, RDS 파일 생성
  README.md
  modudogcat/src/main/resources/application-server.yml
Labels: chore, backend, docs

#118 chore : Modify push branches at gradle.yml
  .github/workflows/gradle.yml
Labels: chore, backend

#121 feat : Seller 회원가입 기능 구현
  src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  src/main/java/com/k5/modudogcat/domain/seller/dto/SellerDto.java
  src/main/java/com/k5/modudogcat/domain/seller/entity/Seller.java
  src/main/java/com/k5/modudogcat/domain/seller/mapper/SellerMapper.java
  src/main/java/com/k5/modudogcat/domain/seller/repository/SellerRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
Labels: backend, feat

#123 "fix : 정규표현식 수정 및 user 유효성 검증 추가"
  src/main/java/com/k5/modudogcat/domain/seller/dto/SellerDto.java
  src/main/java/com/k5/modudogcat/domain/user/controller/UserController.java
  src/main/java/com/k5/modudogcat/domain/user/dto/UserDto.java
Labels: chore, backend

#126 feat : Seller 판매자 페이지 조회 및 정보 수정 기능 구현
  src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  src/main/java/com/k5/modudogcat/domain/seller/dto/SellerDto.java
  src/main/java/com/k5/modudogcat/domain/seller/mapper/SellerMapper.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/domain/user/dto/UserDto.java
  src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
  src/main/resources/static/docs/index.html
Labels: backend, feat

#127 fix : Patch 수정
  src/main/java/com/k5/modudogcat/domain/admin/dto/AdminDto.java
  src/main/java/com/k5/modudogcat/domain/seller/dto/SellerDto.java
Labels: bug, backend

#128 fix : Modify SellerDto patch
  src/main/java/com/k5/modudogcat/domain/seller/dto/SellerDto.java
Labels: bug, backend

#131 Feat/be/product
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderDto.java
  src/main/java/com/k5/modudogcat/domain/order/entity/Order.java
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
  src/main/java/com/k5/modudogcat/domain/order/repository/OrderRepository.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderService.java
  src/main/java/com/k5/modudogcat/domain/product/controller/ProductController.java
  src/main/java/com/k5/modudogcat/domain/product/dto/ProductDto.java
  src/main/java/com/k5/modudogcat/domain/product/entity/Product.java
  src/main/java/com/k5/modudogcat/domain/product/entity/productImage/ProductDetailImage.java
  src/main/java/com/k5/modudogcat/domain/product/entity/productImage/ProductImageController.java
  src/main/java/com/k5/modudogcat/domain/product/entity/productImage/ProductImageRepository.java
  src/main/java/com/k5/modudogcat/domain/product/entity/productImage/ProductImageService.java
  src/main/java/com/k5/modudogcat/domain/product/mapper/ProductMapper.java
  src/main/java/com/k5/modudogcat/domain/product/repository/ProductRepository.java
  src/main/java/com/k5/modudogcat/domain/product/service/ProductService.java
  src/main/java/com/k5/modudogcat/domain/review/controller/ReviewController.java
  src/main/java/com/k5/modudogcat/domain/review/entity/Review.java
  src/main/java/com/k5/modudogcat/domain/review/entity/image/Image.java
  src/main/java/com/k5/modudogcat/domain/review/entity/image/ImageController.java
  src/main/java/com/k5/modudogcat/domain/review/entity/image/ImageRepository.java
  src/main/java/com/k5/modudogcat/domain/review/entity/image/ImageService.java
  src/main/java/com/k5/modudogcat/domain/review/mapper/ReviewMapper.java
  src/main/java/com/k5/modudogcat/domain/review/service/ReviewService.java
  src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
  src/main/resources/application-local.yml
Labels: bug, backend, feat

#133 Fix/be/yml server
  src/main/java/com/k5/modudogcat/domain/product/controller/ProductController.java
  src/main/java/com/k5/modudogcat/domain/product/entity/Product.java
  src/main/java/com/k5/modudogcat/domain/product/mapper/ProductMapper.java
  src/main/resources/application-server.yml
Labels: bug, backend

#134 fix : 관리자 로그인 ID 로 회원가입시, 관리자 권한을 주도록 수정
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
  src/main/java/com/k5/modudogcat/security/util/CustomAuthorityUtils.java
  src/main/resources/application-local.yml
  src/main/resources/application-server.yml
Labels: chore, backend

#135 feat : 관리자 승인 거절 기능 구현 완료
  src/main/java/com/k5/modudogcat/domain/admin/controller/AdminController.java
  src/main/java/com/k5/modudogcat/domain/admin/dto/AdminDto.java
  src/main/java/com/k5/modudogcat/domain/admin/entity/Admin.java
  src/main/java/com/k5/modudogcat/domain/admin/mapper/AdminMapper.java
  src/main/java/com/k5/modudogcat/domain/admin/repository/AdminRepository.java
  src/main/java/com/k5/modudogcat/domain/admin/service/AdminService.java
  src/main/java/com/k5/modudogcat/domain/seller/entity/Seller.java
  src/main/java/com/k5/modudogcat/domain/seller/repository/SellerRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/domain/user/entity/User.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
  src/main/java/com/k5/modudogcat/security/util/CustomAuthorityUtils.java
Labels: bug, backend, feat

#136 fix : AdminService 수정
  src/main/java/com/k5/modudogcat/domain/admin/service/AdminService.java
Labels: bug, backend

#138 Chore/be/seller admin authorization
  src/main/java/com/k5/modudogcat/security/config/SecurityConfig.java
  src/main/resources/application-server.yml
Labels: chore, backend

#139 feat : 관리자 회원가입 시 유저 테이블에 insert
  src/main/java/com/k5/modudogcat/domain/admin/entity/Admin.java
  src/main/java/com/k5/modudogcat/domain/admin/repository/AdminRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/domain/user/controller/UserController.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
  src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
  src/main/java/com/k5/modudogcat/security/util/CustomAuthorityUtils.java
Labels: backend, feat

#140 fix : 관리자 회원가입 시 유저 디비 insert 오류 수정
  src/main/java/com/k5/modudogcat/domain/admin/entity/Admin.java
  src/main/java/com/k5/modudogcat/domain/seller/entity/Seller.java
  src/main/java/com/k5/modudogcat/domain/user/entity/User.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
Labels: bug, backend

#142 feat : cart 엔티티 추가 및 RequestPart 이름 변경
  src/main/java/com/k5/modudogcat/domain/cart/entity/Cart.java
  src/main/java/com/k5/modudogcat/domain/product/controller/ProductController.java
  src/main/java/com/k5/modudogcat/domain/user/Mapper/UserMapper.java
  src/main/java/com/k5/modudogcat/domain/user/entity/User.java
Labels: bug

#148 Chore/be/create and note
  src/main/java/com/k5/modudogcat/domain/cart/controller/CartController.java
  src/main/java/com/k5/modudogcat/domain/order/controller/OrderController.java
  src/main/java/com/k5/modudogcat/domain/product/entity/productImage/ProductDetailImage.java
  src/main/java/com/k5/modudogcat/domain/review/controller/ReviewController.java
  src/main/java/com/k5/modudogcat/domain/user/controller/UserController.java
  src/main/resources/application-server.yml
Labels: chore, backend

#149 feat : 판매자 주문 목록 조회 및 상태 변경 기능 구현
  build.gradle
  src/main/java/com/k5/modudogcat/domain/order/entity/Order.java
  src/main/java/com/k5/modudogcat/domain/order/mapper/OrderMapper.java
  src/main/java/com/k5/modudogcat/domain/product/entity/Product.java
  src/main/java/com/k5/modudogcat/domain/product/mapper/ProductMapper.java
  src/main/java/com/k5/modudogcat/domain/product/repository/ProductRepository.java
  src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  src/main/java/com/k5/modudogcat/domain/seller/entity/Seller.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
  src/main/resources/application-server.yml
  src/test/java/com/k5/modudogcat/ModudogcatApplicationTests.java
  src/test/java/com/k5/modudogcat/util/ApiDocumentUtils.java
Labels: backend, feat

#151 fix : seller FK가 생성되도록 수정
  src/main/java/com/k5/modudogcat/domain/cart/entity/CartProduct.java
  src/main/java/com/k5/modudogcat/domain/product/controller/ProductController.java
  src/main/java/com/k5/modudogcat/domain/product/dto/ProductDto.java
  src/main/java/com/k5/modudogcat/domain/product/mapper/ProductMapper.java
Labels: bug, backend

#156 feat : 장바구니 상품 추가 및 상품수량 변경 기능 구현
  src/main/java/com/k5/modudogcat/domain/cart/controller/CartController.java
  src/main/java/com/k5/modudogcat/domain/cart/dto/CartDto.java
  src/main/java/com/k5/modudogcat/domain/cart/entity/Cart.java
  src/main/java/com/k5/modudogcat/domain/cart/entity/CartProduct.java
  src/main/java/com/k5/modudogcat/domain/cart/mapper/CartMapper.java
  src/main/java/com/k5/modudogcat/domain/cart/repository/CartProductRepository.java
  src/main/java/com/k5/modudogcat/domain/cart/repository/CartRepository.java
  src/main/java/com/k5/modudogcat/domain/cart/service/CartService.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderService.java
  src/main/java/com/k5/modudogcat/domain/product/service/ProductService.java
  src/main/java/com/k5/modudogcat/domain/user/entity/User.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
  src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
Labels: backend, feat

#158 fix : Set 환경변수
  .github/workflows/gradle.yml
  src/main/java/com/k5/modudogcat/domain/seller/entity/Seller.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/resources/application-server.yml
Labels: chore, backend

#160 Feat/be/cart : 상품 중복 검증 및 삭제 기능 구현
  src/main/java/com/k5/modudogcat/ModudogcatApplication.java
  src/main/java/com/k5/modudogcat/domain/cart/controller/CartController.java
  src/main/java/com/k5/modudogcat/domain/cart/repository/CartProductRepository.java
  src/main/java/com/k5/modudogcat/domain/cart/service/CartService.java
  src/main/java/com/k5/modudogcat/domain/user/service/UserService.java
  src/main/java/com/k5/modudogcat/exception/ExceptionCode.java
  src/main/resources/application-server.yml
Labels: backend, feat

#161 Feat/be/order
  src/main/java/com/k5/modudogcat/domain/cart/controller/CartController.java
  src/main/java/com/k5/modudogcat/domain/cart/service/CartService.java
  src/main/java/com/k5/modudogcat/domain/order/controller/OrderController.java
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderDto.java
  src/main/java/com/k5/modudogcat/domain/order/dto/OrderProductDto.java
  src/main/java/com/k5/modudogcat/domain/order/entity/Order.java
  src/main/java/com/k5/modudogcat/domain/order/entity/OrderProduct.java
  src/main/java/com/k5/modudogcat/domain/order/mapper/OrderMapper.java
  src/main/java/com/k5/modudogcat/domain/order/service/OrderService.java
  src/main/java/com/k5/modudogcat/domain/product/dto/ProductDto.java
  src/main/java/com/k5/modudogcat/domain/product/entity/Product.java
  src/main/java/com/k5/modudogcat/domain/seller/controller/SellerController.java
  src/main/java/com/k5/modudogcat/domain/seller/entity/Seller.java
  src/main/java/com/k5/modudogcat/domain/seller/service/SellerService.java
  src/main/java/com/k5/modudogcat/security/config/SecurityConfig.java
Labels: bug, backend, feat

#162 Feat/be/order ( 재고 계산 메서드 제외)
  src/main/java/com/k5/modudogcat/domain/order/service/OrderService.java
Labels: bug, chore, backend
